# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s="Hi there Sam!"
st=s.split()
print(st)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742
print("The diameter of ",planet," is ",diameter," kilometers.")

The diameter of  Earth  is  12742  kilometers.

## 3. In this nest dictionary grab the word "hello"

In [71]:
from collections import defaultdict
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
list=d.get(['k1'][0])
list=list[3]
list=list.get(['tricky'][0])
list=list[3]
list=list.get(['target'][0])
print(list[3])

hello

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [89]:
import numpy as np

arr=np.empty(10,dtype=int)
for x in range(len(arr)):
  arr[x]=0
print(arr)

[0 0 0 0 0 0 0 0 0 0]

In [93]:
import numpy as np

arr=np.empty(5,dtype=int)
for x in range(len(arr)):
   arr[x]=5

print(arr)

[5 5 5 5 5]

## 5. Create an array of all the even integers from 20 to 35

In [96]:
import numpy as np

arr=[]

for x in range(20,35):
 if x%2==0:
  arr.append(x)

print(arr)

[20, 22, 24, 26, 28, 30, 32, 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [105]:
arr=[]
i=0
for x in range(0,3):
  col=[]
  for y in range(0,3):
    col.append(i)
    i+=1
  arr.append(col)


print(arr)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [108]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.append(a,b))

[1 2 3 4 5 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [109]:
import pandas as pd

data={
    "Number":[10,20,30],
    "Day":["Monday","Tuesday","Wednesday"]
}

print(pd.DataFrame(data))

   Number        Day
0      10     Monday
1      20    Tuesday
2      30  Wednesday

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [119]:
import pandas as pd
import numpy as np

ser=np.arange(1,32)
seri=pd.Series(data=ser)
ser1=np.arange(1,11)
seri1=pd.Series(data=ser1)
seri=pd.DataFrame(seri.append(seri1,ignore_index=True))
print(seri)

     0
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
12  13
13  14
14  15
15  16
16  17
17  18
18  19
19  20
20  21
21  22
22  23
23  24
24  25
25  26
26  27
27  28
28  29
29  30
30  31
31   1
32   2
33   3
34   4
35   5
36   6
37   7
38   8
39   9
40  10

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [122]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
print(pd.DataFrame(lists,columns=["Sno","Name","Mark"]))

   Sno Name  Mark
0    1  aaa    22
1    2  bbb    25
2    3  ccc    24